"""Syntax colouring for the SQL and Mermaid text views (QSyntaxHighlighter).

The text is generated by the app, so a handful of regular expressions cover
it: no parser, no extra dependency. Colours come from the palette's
brightness and clear 4.5:1 on the editor background in both schemes.
"""

from __future__ import annotations

import re

from PySide6.QtGui import (
    QColor,
    QFont,
    QPalette,
    QSyntaxHighlighter,
    QTextCharFormat,
)

# Token colours per scheme, each 4.5:1 or better on Base (#ffffff / #1e1f22).
_COLOURS = {
    "light": {
        "keyword": "#0b4fb3",  # 7.54
        "name": "#6f2dbd",  # 7.54
        "string": "#a31515",  # 7.85
        "number": "#116329",  # 7.39
        "comment": "#5f6b76",  # 5.45
        "punct": "#57606a",  # 6.39
    },
    "dark": {
        "keyword": "#6aa7ff",  # 6.74
        "name": "#c79bf2",  # 7.38
        "string": "#f2a37b",  # 8.08
        "number": "#8fd68f",  # 9.56
        "comment": "#9aa3ad",  # 6.45
        "punct": "#a8b0b8",  # 7.51
    },
}

_SQL_KEYWORDS = (
    "select top from where join inner left right full outer cross on and or not "
    "as in is null like between exists order by group having distinct union all "
    "insert into values update set delete create alter drop table view index "
    "with case when then else end cast convert coalesce isnull count sum min max "
    "avg asc desc declare begin commit rollback go use schema object_id "
    "sys information_schema"
).split()

_MERMAID_KEYWORDS = ("erDiagram", "PK", "FK", "UK", "direction", "LR", "RL", "TB", "BT")


class _RuleHighlighter(QSyntaxHighlighter):
    """Colours tokens by regex rules, plus one multi-line comment form."""

    # (pattern, token) pairs, applied in order; later rules win overlaps.
    RULES: list[tuple[str, str]] = []
    BLOCK_COMMENT: tuple[str, str] | None = None  # (start, end) regexes
    # Past this size the text stays plain: colouring a whole-schema dump of
    # several MB would stall the window for little benefit.
    MAX_CHARS = 400_000

    def __init__(self, document, widget):
        super().__init__(document)
        self._widget = widget
        self._rules = [(re.compile(p), t) for p, t in self.RULES]
        self._formats: dict[str, QTextCharFormat] = {}
        self.retheme()

    def retheme(self):
        """Pick colours for the widget's current palette and redraw."""
        dark = self._widget.palette().color(QPalette.Base).lightness() < 128
        colours = _COLOURS["dark" if dark else "light"]
        self._formats = {}
        for token, colour in colours.items():
            fmt = QTextCharFormat()
            fmt.setForeground(QColor(colour))
            if token == "keyword":
                fmt.setFontWeight(QFont.DemiBold)
            if token == "comment":
                fmt.setFontItalic(True)
            self._formats[token] = fmt
        self.rehighlight()

    def highlightBlock(self, text):  # noqa: N802 (Qt naming)
        if self.document().characterCount() > self.MAX_CHARS:
            return
        for pattern, token in self._rules:
            for match in pattern.finditer(text):
                start, end = match.span(match.lastindex or 0)
                self.setFormat(start, end - start, self._formats[token])
        if self.BLOCK_COMMENT:
            self._block_comments(text)

    def _block_comments(self, text):
        """/* ... */ across lines: block state 1 means "inside a comment"."""
        opening, closing = (re.compile(p) for p in self.BLOCK_COMMENT)
        fmt = self._formats["comment"]
        self.setCurrentBlockState(0)
        if self.previousBlockState() == 1:
            start, skip = 0, 0
        else:
            m = opening.search(text)
            start, skip = (m.start(), 2) if m else (-1, 0)
        while start >= 0:
            m = closing.search(text, start + skip)
            if m is None:
                self.setCurrentBlockState(1)
                self.setFormat(start, len(text) - start, fmt)
                return
            self.setFormat(start, m.end() - start, fmt)
            nxt = opening.search(text, m.end())
            start, skip = (nxt.start(), 2) if nxt else (-1, 0)


class SqlHighlighter(_RuleHighlighter):
    """T-SQL as the app writes it: keywords, [bracketed] names, literals, comments."""

    RULES = [
        (r"\b\d+(?:\.\d+)?\b", "number"),
        (r"[(),.;=*]", "punct"),
        (r"(?i)\b(?:" + "|".join(_SQL_KEYWORDS) + r")\b", "keyword"),
        (r"\[(?:[^\]]|\]\])*\]", "name"),
        (r"N?'(?:[^']|'')*'", "string"),
        (r"--.*$", "comment"),
    ]
    BLOCK_COMMENT = (r"/\*", r"\*/")


class MermaidHighlighter(_RuleHighlighter):
    """Mermaid erDiagram source: keywords, relationship arrows, keys, notes."""

    RULES = [
        (r"[{}:]", "punct"),
        (r"[|}o]{1,2}(?:--|\.\.)[|{o]{1,2}", "keyword"),
        (r"\b(?:" + "|".join(_MERMAID_KEYWORDS) + r")\b", "keyword"),
        (r"^\s*([A-Za-z_][\w]*)\s*(?:\{|[|}o]{1,2}(?:--|\.\.))", "name"),
        (r"\b([A-Za-z_]\w*)\s*:", "name"),
        (r'"[^"]*"', "string"),
        (r"%%.*$", "comment"),
    ]
